common:
## python -c 'import crypt; print crypt.crypt("password", "password")';
  linux_user: "user"
  linux_user_password: "12vjy8B6VZQUU" #123123
  root_password: "12vjy8B6VZQUU" #123123
  domain_name: "xxxxx.com"
