---
- hostname:
    name: "{{ ansible_hostname }}"

# K8s Master Scripts
- include: master-up.yml

# K8s Network Controller Scripts
- include: calico.yml

# K8s Dashboard Scripts
#- include: dashboard.yml
#- include: heapster.yml

- name: Don't run anything on Master K8s with Taint
  shell: |
    kubectl taint nodes --all node-role.kubernetes.io/master-
  ignore_errors: yes

- include: example-guestbook.yml
