---
- hostname:
    name: "{{ ansible_hostname }}"

- name: Master-Up Template Scripts
  template:
    src: master-up.sh
    dest: ~/master-up.sh

- name: Flannel Network Template Scripts
  template:
    src: flannel.sh
    dest: ~/flannel.sh

- name: Executes Master-Up Scripts
  shell: master-up.sh >> master-up.logs
  chdir: "/{{ ansible_user }}"
  args:
    chdir: "/{{ ansible_user }}"
    creates: master-up.logs

- name: Executes Flannel Scripts
  shell: flannel.sh >> flannel.logs
  chdir: "/{{ ansible_user }}"
  args:
    chdir: "/{{ ansible_user }}"
    creates: flannel.logs
