---
- name: Clean Yum Transactions
  shell: |
    yum-complete-transaction --cleanup-only
  ignore_errors: yes

- name: Un-install All Kubernetes Repository
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
   - docker-ce
   - kubelet
   - kubeadm
   - kubectl

- name: Clean Mounted Memory in Kubernetes and Docker
  shell: |
    for x in `df -h | grep kube`; do umount `echo $x | grep lib | grep kube`; done
    for x in `df -h | grep docker`; do umount `echo $x | grep lib | grep docker`; done
  ignore_errors: yes

- name: Removing Kubernetes Directory
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/kubernetes
    - /etc/systemd/system/kubelet.service*
    - /var/lib/kubelet
    - /var/lib/calico
    - /var/lib/etcd
    - /var/lib/docker*
    - "/{{ ansible_user }}/.kube"
    - "/{{ ansible_user }}/.master-up.runs"
  register: reboot_task

- name: Reboot Task
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: reboot_task is changed

- name: Wait for Reboot
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  when: reboot_task is changed
