---
# Auto Join 
- name: Copy file from Localhost to Worker
  copy:
    src: "/tmp/autojoin.sh" #from Localhost
    dest: "/{{ ansible_user }}/autojoin.sh"

- name: Runs Autojoin.sh to Joining Master Cluster
  shell: |
    /bin/bash "/{{ ansible_user }}/autojoin.sh"
  ignore_errors: yes
