---
# Auto Join Logs
# - name: Copy files from Master to Worker for Auto Join Worker
#   synchronize: src=source dest=destination dirs=yes use_ssh_args=yes
#   delegate_to: "{{ source_ip }}"
#
#   {% for hosts in groups['master'] %}
#     {{ hostvars[hosts]['ansible_host'] }}
#   {% endfor %}
